"""empty message

Revision ID: 59f497c7f81b
Revises: 
Create Date: 2019-01-16 21:27:54.594806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59f497c7f81b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estabelecimento',
    sa.Column('idEstabelecimento', sa.Integer(), nullable=False),
    sa.Column('nmEstabelecimento', sa.String(length=255), nullable=True),
    sa.Column('nrCodigoOficial', sa.String(length=255), nullable=True),
    sa.Column('idPais', sa.Integer(), nullable=True),
    sa.Column('idUf', sa.Integer(), nullable=True),
    sa.Column('idMunicipio', sa.Integer(), nullable=True),
    sa.Column('nmLocalidade', sa.String(length=255), nullable=True),
    sa.Column('nrLatitude', sa.Float(), nullable=True),
    sa.Column('nrLongitude', sa.Float(), nullable=True),
    sa.Column('stAtivo', sa.Boolean(), nullable=True),
    sa.Column('idCliente', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('idEstabelecimento')
    )
    op.create_table('produtor',
    sa.Column('idProdutor', sa.Integer(), nullable=False),
    sa.Column('nrDocumento', sa.String(length=255), nullable=True),
    sa.Column('nmProdutor', sa.String(length=255), nullable=True),
    sa.Column('nrTelefone', sa.String(length=255), nullable=True),
    sa.Column('dsEmail', sa.String(length=255), nullable=True),
    sa.Column('cdEstabelecimento', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cdEstabelecimento'], ['estabelecimento.idEstabelecimento'], ),
    sa.PrimaryKeyConstraint('idProdutor')
    )
    op.create_table('unidadeExploracao',
    sa.Column('idUnidadeExploracao', sa.Integer(), nullable=False),
    sa.Column('nrUnidadeExploracao', sa.Integer(), nullable=True),
    sa.Column('qtCapacidadeAlojamento', sa.Integer(), nullable=True),
    sa.Column('csTipoUnidadeExploracao', sa.String(length=255), nullable=True),
    sa.Column('stAtiva', sa.Boolean(), nullable=True),
    sa.Column('csTipoAnimal', sa.String(length=2), nullable=True),
    sa.Column('cdEstabelecimento', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cdEstabelecimento'], ['estabelecimento.idEstabelecimento'], ),
    sa.PrimaryKeyConstraint('idUnidadeExploracao')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unidadeExploracao')
    op.drop_table('produtor')
    op.drop_table('estabelecimento')
    # ### end Alembic commands ###
